apiVersion: v1
kind: Service
metadata:
  name: test-api-service
  labels:
    app: test-api
  annotations:
spec:
  type: NodePort
  selector:
    app: test-api
  ports:
  - port: 8080
    targetPort: 8080
    